env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
globals:
  config: false
  Immutable: false
  http: false
  _: false
  moment: false
  jQuery: false
rules:
  strict: 0
  'no-unused-vars': off
  'no-console': off
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - never
